import Head from 'next/head';
import Image from 'next/image';
import Default from '../layouts/Default';

import img from '../public/2.jpg';

export default function Home() {
	return (
		<>
			<Head>
				<title>Jane Doe</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/logo.favicon.png" />
				<script src="https://cdn.tailwindcss.com" />
			</Head>
			<Default>
        <div className="bg-red-100">
				<div className="container py-12 mx-auto px-4 md:px-12">
					<div className="flex flex-wrap -mx-1 lg:-mx-4">
						<div className="py-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
							<article className="overflow-hidden rounded-lg shadow-lg bg-white">
								<a href="#">
									<Image
										alt="Placeholder"
										className="block h-auto w-full"
										src={img}
									/>
								</a>

								<header className="flex items-center justify-between leading-tight p-2 md:p-4">
									<h1 className="text-lg">
										<a className="no-underline hover:underline text-black" href="#">
											Article Title
										</a>
									</h1>
									<p className="text-grey-darker text-sm">11/1/19</p>
								</header>

								<button className="bg-rose-500 hover:bg-rose-600 text-white font-bold py-2 px-4 rounded">Add to Cart</button>
							</article>
						</div>

						<div className="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
							<article className="overflow-hidden rounded-lg shadow-lg bg-white">
								<a href="#">
									<Image
										alt="Placeholder"
										className="block h-auto w-full"
										src={img}
									/>
								</a>

								<header className="flex items-center justify-between leading-tight p-2 md:p-4">
									<h1 className="text-lg">
										<a className="no-underline hover:underline text-black" href="#">
											Article Title
										</a>
									</h1>
									<p className="text-grey-darker text-sm">11/1/19</p>
								</header>

								<button className="bg-rose-500 hover:bg-rose-600 text-white font-bold py-2 px-4 rounded">Add to Cart</button>
							</article>
						</div>

						<div className="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
							<article className="overflow-hidden rounded-lg shadow-lg bg-white">
								<a href="#">
									<Image
										alt="Placeholder"
										className="block h-auto w-full"
										src={img}
									/>
								</a>

								<header className="flex items-center justify-between leading-tight p-2 md:p-4">
									<h1 className="text-lg">
										<a className="no-underline hover:underline text-black" href="#">
											Article Title
										</a>
									</h1>
									<p className="text-grey-darker text-sm">11/1/19</p>
								</header>

								<button className="bg-rose-500 hover:bg-rose-600 text-white font-bold py-2 px-4 rounded">Add to Cart</button>
							</article>
						</div>

						<div className="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
							<article className="overflow-hidden rounded-lg shadow-lg bg-white">
								<a href="#">
									<Image
										alt="Placeholder"
										className="block h-auto w-full"
										src={img}
									/>
								</a>

								<header className="flex items-center justify-between leading-tight p-2 md:p-4">
									<h1 className="text-lg">
										<a className="no-underline hover:underline text-black" href="#">
											Article Title
										</a>
									</h1>
									<p className="text-grey-darker text-sm">11/1/19</p>
								</header>

								<button className="bg-rose-500 hover:bg-rose-600 text-white font-bold py-2 px-4 rounded">Add to Cart</button>
							</article>
						</div>

						<div className="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
							<article className="overflow-hidden rounded-lg shadow-lg bg-white">
								<a href="#">
									<Image
										alt="Placeholder"
										className="block h-auto w-full"
										src={img}
									/>
								</a>

								<header className="flex items-center justify-between leading-tight p-2 md:p-4">
									<h1 className="text-lg">
										<a className="no-underline hover:underline text-black" href="#">
											Article Title
										</a>
									</h1>
									<p className="text-grey-darker text-sm">11/1/19</p>
								</header>

								<button className="bg-rose-500 hover:bg-rose-600 text-white font-bold py-2 px-4 rounded">Add to Cart</button>
							</article>
						</div>

						<div className="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
							<article className="overflow-hidden rounded-lg shadow-lg bg-white">
								<a href="#">
									<Image
										alt="Placeholder"
										class="block h-auto w-full"
										src={img}
									/>
								</a>

								<header class="flex items-center justify-between leading-tight p-2 md:p-4">
									<h1 class="text-lg">
										<a class="no-underline hover:underline text-black" href="#">
											Article Title
										</a>
									</h1>
									<p class="text-grey-darker text-sm">11/1/19</p>
								</header>

								<button className="bg-rose-500 hover:bg-rose-600 text-white font-bold py-2 px-4 rounded">Add to Cart</button>
							</article>
						</div>
					</div>
					</div>
				</div>
			</Default>
		</>
	);
}
