import Head from 'next/head';

import Default from '../layouts/Default';
// import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<>
			<Head>
				<title>Jane Doe</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/logo.favicon.png" />
				<script src="https://cdn.tailwindcss.com" />
			</Head>
			<Default>
				<div class="container bg-red-100 py-12 mx-auto px-4 md:px-12">
					<div class="flex flex-wrap -mx-1 lg:-mx-4">
						<div class="py-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
							<article class="overflow-hidden rounded-lg shadow-lg bg-white">
								<a href="#">
									<img
										alt="Placeholder"
										class="block h-auto w-full"
										src="https://picsum.photos/600/400/?random"
									/>
								</a>

								<header class="flex items-center justify-between leading-tight p-2 md:p-4">
									<h1 class="text-lg">
										<a class="no-underline hover:underline text-black" href="#">
											Article Title
										</a>
									</h1>
									<p class="text-grey-darker text-sm">11/1/19</p>
								</header>

								<footer class="flex items-center justify-between leading-none p-2 md:p-4">
									<a
										class="flex items-center no-underline hover:underline text-black"
										href="#"
									>
										<img
											alt="Placeholder"
											class="block rounded-full"
											src="https://picsum.photos/32/32/?random"
										/>
										<p class="ml-2 text-sm">Author Name</p>
									</a>
									<a
										class="no-underline text-grey-darker hover:text-red-dark"
										href="#"
									></a>
								</footer>
							</article>
						</div>

						<div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
							<article class="overflow-hidden rounded-lg shadow-lg bg-white">
								<a href="#">
									<img
										alt="Placeholder"
										class="block h-auto w-full"
										src="https://picsum.photos/600/400/?random"
									/>
								</a>

								<header class="flex items-center justify-between leading-tight p-2 md:p-4">
									<h1 class="text-lg">
										<a class="no-underline hover:underline text-black" href="#">
											Article Title
										</a>
									</h1>
									<p class="text-grey-darker text-sm">11/1/19</p>
								</header>

								<footer class="flex items-center justify-between leading-none p-2 md:p-4">
									<a
										class="flex items-center no-underline hover:underline text-black"
										href="#"
									>
										<img
											alt="Placeholder"
											class="block rounded-full"
											src="https://picsum.photos/32/32/?random"
										/>
										<p class="ml-2 text-sm">Author Name</p>
									</a>
									<a
										class="no-underline text-grey-darker hover:text-red-dark"
										href="#"
									></a>
								</footer>
							</article>
						</div>

						<div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
							<article class="overflow-hidden rounded-lg shadow-lg bg-white">
								<a href="#">
									<img
										alt="Placeholder"
										class="block h-auto w-full"
										src="https://picsum.photos/600/400/?random"
									/>
								</a>

								<header class="flex items-center justify-between leading-tight p-2 md:p-4">
									<h1 class="text-lg">
										<a class="no-underline hover:underline text-black" href="#">
											Article Title
										</a>
									</h1>
									<p class="text-grey-darker text-sm">11/1/19</p>
								</header>

								<footer class="flex items-center justify-between leading-none p-2 md:p-4">
									<a
										class="flex items-center no-underline hover:underline text-black"
										href="#"
									>
										<img
											alt="Placeholder"
											class="block rounded-full"
											src="https://picsum.photos/32/32/?random"
										/>
										<p class="ml-2 text-sm">Author Name</p>
									</a>
									<a
										class="no-underline text-grey-darker hover:text-red-dark"
										href="#"
									></a>
								</footer>
							</article>
						</div>

						<div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
							<article class="overflow-hidden rounded-lg shadow-lg bg-white">
								<a href="#">
									<img
										alt="Placeholder"
										class="block h-auto w-full"
										src="https://picsum.photos/600/400/?random"
									/>
								</a>

								<header class="flex items-center justify-between leading-tight p-2 md:p-4">
									<h1 class="text-lg">
										<a class="no-underline hover:underline text-black" href="#">
											Article Title
										</a>
									</h1>
									<p class="text-grey-darker text-sm">11/1/19</p>
								</header>

								<footer class="flex items-center justify-between leading-none p-2 md:p-4">
									<a
										class="flex items-center no-underline hover:underline text-black"
										href="#"
									>
										<img
											alt="Placeholder"
											class="block rounded-full"
											src="https://picsum.photos/32/32/?random"
										/>
										<p class="ml-2 text-sm">Author Name</p>
									</a>
									<a
										class="no-underline text-grey-darker hover:text-red-dark"
										href="#"
									></a>
								</footer>
							</article>
						</div>

						<div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
							<article class="overflow-hidden rounded-lg shadow-lg bg-white">
								<a href="#">
									<img
										alt="Placeholder"
										class="block h-auto w-full"
										src="https://picsum.photos/600/400/?random"
									/>
								</a>

								<header class="flex items-center justify-between leading-tight p-2 md:p-4">
									<h1 class="text-lg">
										<a class="no-underline hover:underline text-black" href="#">
											Article Title
										</a>
									</h1>
									<p class="text-grey-darker text-sm">11/1/19</p>
								</header>

								<footer class="flex items-center justify-between leading-none p-2 md:p-4">
									<a
										class="flex items-center no-underline hover:underline text-black"
										href="#"
									>
										<img
											alt="Placeholder"
											class="block rounded-full"
											src="https://picsum.photos/32/32/?random"
										/>
										<p class="ml-2 text-sm">Author Name</p>
									</a>
									<a
										class="no-underline text-grey-darker hover:text-red-dark"
										href="#"
									></a>
								</footer>
							</article>
						</div>

						<div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
							<article class="overflow-hidden rounded-lg shadow-lg bg-white">
								<a href="#">
									<img
										alt="Placeholder"
										class="block h-auto w-full"
										src="https://picsum.photos/600/400/?random"
									/>
								</a>

								<header class="flex items-center justify-between leading-tight p-2 md:p-4">
									<h1 class="text-lg">
										<a class="no-underline hover:underline text-black" href="#">
											Article Title
										</a>
									</h1>
									<p class="text-grey-darker text-sm">11/1/19</p>
								</header>

								<footer class="flex items-center justify-between leading-none p-2 md:p-4">
									<a
										class="flex items-center no-underline hover:underline text-black"
										href="#"
									>
										<img
											alt="Placeholder"
											class="block rounded-full"
											src="https://picsum.photos/32/32/?random"
										/>
										<p class="ml-2 text-sm">Author Name</p>
									</a>
									<a
										class="no-underline text-grey-darker hover:text-red-dark"
										href="#"
									></a>
								</footer>
							</article>
						</div>
					</div>
				</div>
			</Default>
		</>
	);
}
